### ISSUE TITLE
Project export not working in  Redmine 3.2.0.stable version

### ISSUE THREAD

**Issue by jva5007** [yukkyna/redmine-export-project-data#10]
Hi,

This plugin is not working in the latest version of redmine(3.2.0). The error message is updated below.

"export project data"
rake aborted!
ActiveRecord::RecordNotFound: Couldn't find all Projects with 'id': (first, {:conditions=>["identifier = ?", "projectname"]}) (found 0 results, but was looking for 2)
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/activerecord-4.2.5/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/activerecord-4.2.5/lib/active_record/relation/finder_methods.rb:467:in`find_some'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/activerecord-4.2.5/lib/active_record/relation/finder_methods.rb:426:in `find_with_ids'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/activerecord-4.2.5/lib/active_record/relation/finder_methods.rb:71:in`find'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/activerecord-4.2.5/lib/active_record/querying.rb:3:in `find'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/activerecord-4.2.5/lib/active_record/core.rb:128:in`find'
/path/to/redmine/app/models/project.rb:310:in `find'
/path/to/redmine/lib/tasks/export_project_data.rake:35:in`block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in`<main>'
Tasks: TOP => project_data:export
(See full trace by running task with --trace)

This code was very helpful for the older versions. Please update the code, so that we can use this in the later versions also.

Thanks
JVA

**Comment by crow-misia** [comment]
Thank you for reporting the problem.

Because I am busy, the response will be delayed, but I will try to fix it.

Thanks.
